global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quarkus'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['back:8080']

  - job_name: 'mysqld'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
